name: 'Okta-Signin-Widget Build'
on: push
jobs:
  install:
    name: 'install deps'
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies with yarn
        run: yarn
  test:
    name: 'run test suites'
    runs-on: ubuntu-latest
    container: weboaks/node-karma-protractor-chrome:debian-root-node14
    needs: install
    strategy:
      matrix:
        include:
          - name: lint
            command: lint
          - name: karma
            command: 'test -t karma'
          - name: jest
            command: 'test -t jest'
          - name: testcafe
            command: 'test:testcafe-ci'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies with yarn
        run: yarn

      - name: Run test command
        run: yarn ${{ matrix.command }}

      - name: Archive test report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: ${{ matrix.name }}-report
          path: ${{ github.workspace }}/test-reports/**/*
